### ISSUE TITLE
sems server did not relay DTMF (RTP Event Packets)

### ISSUE THREAD

**Issue by hamidrhashmi** [sems-server/sems#154] opened 2020-03-26 09:33 UTC
If User A calls User B and User A sends some DTMF to User B. User B was able to receive it **but** if User B sends DTMF to User A sems-server **didn't** relay it to User A. RTP Event Packets dropped on sems-server.

**Comment by juha-h** [comment] 2020-03-29 08:32
Hamid R. Hashmi writes:

> If User A calls User B and User A sends some DTMF to User B. User B
> was able to receive it **but** if User B sends DTMF to User A
> sems-server **didn't** relay it to User A. RTP Event Packets dropped
> on sems-server.

Show the app you are using.

**Comment by hamidrhashmi** [comment] 2020-03-30 05:42
application = sbc

**Comment by juha-h** [comment] 2020-03-31 13:52
Hamid R. Hashmi writes:

> application = sbc

How does your sbc profile look like?

**Comment by hamidrhashmi** [comment] 2020-04-03 10:59
Please see the profile details below

```
outbound_proxy=sip:mo@$si:$sp
next_hop_ip=$si
next_hop_port=$sp
enable_rtprelay=yes
header_filter=whitelist
header_list=Diversion,P-Asserted-Identity,Privacy,Allow,Event,Expires,Accept,User-Agent,Subscription-State,P-Access-Network-Info,P-Route,C-Params,X-C-Params,Feature-Caps,P-Charging-Vector,X-Session-Case,P-Called-Party,Alert-info,Refer-To,Referred-By
message_filter=blacklist
message_list=SUBSCRIBE
sdp_filter=whitelist
sdpfilter_list=g722,pcma,pcmu,gsm,amr,amr-wb,amr-wb/16000,h264,telephone-event
codec_preference=g722,amr-wb,amr-wb/16000,pcmu,pcma,gsm,amr
sdp_anonymize=yes
sdp_alines_filter=blacklist
sdp_alinesfilter_list=crypto,nortpproxy

enable_aleg_session_timer=no
aleg_session_expires=300
aleg_minimum_timer=90
aleg_maximum_timer=1800
aleg_session_refresh_method=UPDATE_FALLBACK_INVITE
aleg_accept_501_reply=yes

enable_session_timer=no
session_expires=900
minimum_timer=300
maximum_timer=7200
session_refresh_method=UPDATE_FALLBACK_INVITE
accept_501_reply=yes
```

**Comment by juha-h** [comment] 2020-04-15 05:40
I was not able to reproduce your issue using this simple sbc profile of mine:
```
call_control=$H(P-Call-Control)
enable_rtprelay=yes
```
I suspect your sdp* lines.  Try adding sdp stuff incrementally until you hit the issue. Are you sure that 
telephone-event does not require /8000 suffix?

**Comment by juha-h** [comment] 2020-04-15 05:42
About telephone-event/16000, I don't know, since my SIP UAs use telephone-event/8000.  Try with that and see if it works.

**Comment by hamidrhashmi** [comment] 2020-04-17 02:59
The following line is causing the issue
```
codec_preference=g722,amr-wb,amr-wb/16000,pcmu,pcma,gsm,amr
```

and there is no option to blacklist telephone-event/16000 only. I tried adding telephone-event/8000 in whitelist list but it removed all telephone-event codecs from INVITE.

**Comment by juha-h** [comment] 2020-04-19 11:57
Hamid R. Hashmi writes:

> The following line is causing the issue
> ```
> codec_preference=g722,amr-wb,amr-wb/16000,pcmu,pcma,gsm,amr
> ```
> 
> and there is no option to blacklist telephone-event/16000 only. I
> tried adding telephone-event/8000 in whitelist list but it removed all
> telephone-event codecs from INVITE.

I looked at the code and currently sdp filtering is based on encoding name
only:
```
	string c = p_it->encoding_name;
	std::transform(c.begin(), c.end(), c.begin(), ::tolower);

	bool is_filtered =  (sdpfilter == Whitelist) ^
	  (sdpfilter_list.find(c) != sdpfilter_list.end());
```
Are you saying that there is more than one telephone-event attribute in
the sdp and you want to filter some of them based on the rate?

**Comment by hamidrhashmi** [comment] 2020-04-20 08:53
Yes, there are two issues

1. As you already said, there are two telephone-event attributes in the SDP and these telephone-event attributes didn't filter on the rate.

2. Adding a "codec_performance" line causing some issue that is didn't relay telephone-event/8000 packets.

**Comment by juha-h** [comment] 2020-04-20 10:18
Hamid R. Hashmi writes:

> 1. As you already said, there are two telephone-event attributes in
> the SDP and these telephone-event attributes didn't filter on the
> rate.

Supporting rates in sdp_filter_list would be a new feature.  You need to
find someone to create a pull request.

> 2. Adding a "codec_performance" line causing some issue that is didn't
> relay telephone-event/8000 packets.

Have you tried to add telephone-event to codec_pererence line?

**Comment by juha-h** [comment] 2020-04-21 10:09
> 2. Adding a "codec_performance" line causing some issue that is didn't relay telephone-event/8000 packets.

I tried by adding line
```
codec_preference=pcmu,pcma,opus
```
to my profile and telephone-event/8000 events worked fine both ways.

**Comment by juha-h** [comment] 2020-04-29 15:26
I'm closing this, since codec filtering based on rates is a new feature that requites a pull request.  The other issue I have not been able to reproduce and there has not been exact further information about it.

**Closed by juha-h** 2020-04-29 15:26 UTC
